# Generated by Django 5.2.7 on 2025-11-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
