# Generated by Django 5.2.7 on 2025-11-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_addstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='email',
            new_name='your_email',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='regNo',
            new_name='yourregNo',
        ),
    ]
