# Generated by Django 5.2.7 on 2025-11-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_rename_fname_addstudent_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='yourregNo',
            new_name='your_regNo',
        ),
    ]
