# Generated by Django 5.2.7 on 2025-11-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_rename_yourregno_addstudent_your_regno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='your_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='your_regNo',
            new_name='regNo',
        ),
    ]
