# Generated by Django 5.2.7 on 2025-11-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_your_email_addstudent_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='email',
            new_name='std_email',
        ),
        migrations.RenameField(
            model_name='addstudent',
            old_name='regNo',
            new_name='std_regNo',
        ),
    ]
