# Generated by Django 5.2.7 on 2025-11-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_rename_fname_addstudent_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='std_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
