# Generated by Django 5.2.7 on 2025-11-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_addstudent_std_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='std_email',
            field=models.EmailField(max_length=254),
        ),
    ]
